# -*- coding: utf-8 -*-
"""Φυσική ακτινοβολιών.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXRtraCHfGFDgHsE3x5mF4aA99pKlkYW
"""

import pandas as pd
from urllib.request import Request, urlopen
import plotly.graph_objects as go

# --- CONFIGURATION & CONSTANTS ---
API_BASE_URL = "https://nds.iaea.org/relnsd/v0/data?"
MASS_PROTON = 938.27208816  # MeV/c^2
MASS_NEUTRON = 939.56542052 # MeV/c^2

print("Initializing Nuclear Data Viewer...")

def fetch_csv_data(query_string):
    """Fetches data from the IAEA LiveChart API and returns a Pandas DataFrame."""
    req = Request(API_BASE_URL + query_string)
    req.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)')
    return pd.read_csv(urlopen(req))

# Pre-load ground state data for all isotopes
all_nuclides_data = fetch_csv_data('fields=ground_states&nuclides=all')

# --- PHYSICS CALCULATIONS ---

def calc_mass(A, Z):
    """Calculates the mass of a nucleus in MeV/c^2."""
    try:
        N = A - Z
        condition = (all_nuclides_data['z'] == Z) & (all_nuclides_data['n'] == N)
        binding_energy_kev = float(all_nuclides_data['binding'][condition].iloc[0])
        binding_energy_mev = binding_energy_kev / 1000.0
        return (N * MASS_NEUTRON) + (Z * MASS_PROTON) - (A * binding_energy_mev)
    except Exception:
        return None

def calc_separation_energy(A, Z, target_a, target_z):
    """Calculates the separation energy for a specific particle."""
    mass_initial = calc_mass(A, Z)
    mass_residual = calc_mass(A - target_a, Z - target_z)

    if target_z == 0:
        mass_particle = target_a * MASS_NEUTRON
    elif target_a == target_z:
        mass_particle = target_a * MASS_PROTON
    else:
        mass_particle = calc_mass(target_a, target_z)

    if mass_initial is None or mass_residual is None or mass_particle is None:
        return None

    return mass_residual + mass_particle - mass_initial

def get_excited_states(isotope, max_mev):
    """Fetches excited energy levels up to a maximum MeV."""
    df_levels = fetch_csv_data(f"fields=levels&nuclides={isotope}")
    try:
        valid_levels = df_levels[df_levels['energy'] <= max_mev * 1000]
        return valid_levels[['energy', 'jp']]
    except Exception:
        return None

# --- DISPLAY FUNCTIONS ---

def print_isotope_info(isotope):
    """Prints physical properties and decay modes of the isotope."""
    df_iso = fetch_csv_data(f"fields=ground_states&nuclides={isotope}")
    print(f"==============================================  {isotope}")
    try:
        Z = int(df_iso['z'].iloc[0])
        N = int(df_iso['n'].iloc[0])
        A = Z + N
        binding = float(df_iso['binding'].iloc[0])
        mass = Z * MASS_PROTON + N * MASS_NEUTRON - A * (binding / 1000.0)
        half_life = df_iso['half_life_sec'].iloc[0]

        print(f"  A : {A:3d}, Z : {Z:3d}, N : {N:3d}, Mass : {mass:.4f} MeV")
        print(f"Jpi : {str(df_iso['jp'].iloc[0]):>3s},    half-live : {half_life} sec")

        # Separation energies
        sn = calc_separation_energy(A, Z, 1, 0)
        sp = calc_separation_energy(A, Z, 1, 1)
        print(f"Sn  : {sn:8.3f} MeV, Sp  : {sp:8.3f} MeV")

        s2n = calc_separation_energy(A, Z, 2, 0)
        s2p = calc_separation_energy(A, Z, 2, 2)
        sd = calc_separation_energy(A, Z, 2, 1)
        print(f"S2n : {s2n:8.3f} MeV, S2p : {s2p:8.3f} MeV, Sd : {sd:8.3f} MeV")

        print(f"   magnetic dipole :  {df_iso['magnetic_dipole'].iloc[0]}  mu N")
        print(f"electric quadruple :  {df_iso['electric_quadrupole'].iloc[0]}  barn")

        if half_life != ' ' and float(half_life) > 0:
            print('------------ decay mode:')
            for i in range(1, 4):
                d_mode = df_iso[f"decay_{i}"].iloc[0]
                d_perc = df_iso[f"decay_{i}_%"].iloc[0]
                if pd.notna(d_mode) and str(d_mode).strip():
                    print(f"{d_mode:>5s}  {d_perc} %")
            print('-------------------------')
    except Exception:
        print("Data not found or error parsing.")
    print("====================================================")

def plot_energy_levels(isotope, max_mev):
    """Draws an interactive Plotly diagram of the energy levels."""
    df_iso = fetch_csv_data(f"fields=ground_states&nuclides={isotope}")

    Z = int(df_iso['z'].iloc[0])
    N = int(df_iso['n'].iloc[0])
    symbol = df_iso['symbol'].iloc[0]
    A = Z + N

    sn = calc_separation_energy(A, Z, 1, 0)
    sp = calc_separation_energy(A, Z, 1, 1)

    levels_data = get_excited_states(isotope, max_mev)
    if levels_data is None:
        print("Error fetching levels.")
        return

    energies = (levels_data['energy'] / 1000.0).reset_index(drop=True)
    spins = levels_data['jp'].reset_index(drop=True)

    plot_height = 400
    font_size = 20
    y_min = -1

    fig = go.Figure()
    fig.update_layout(plot_bgcolor='white', width=600, height=plot_height, margin=dict(l=0, r=0, t=0, b=0))
    fig.update_layout(showlegend=False)
    fig.update_xaxes(showline=False, visible=False, range=[-1, 3])
    fig.update_yaxes(showline=True, visible=True, range=[y_min, max_mev + 1])

    last_idx = energies.last_valid_index()
    if last_idx is None:
        print("No excited levels found in this range.")
        return

    # Anti-overlap logic for labels
    font_size_mev = font_size / plot_height * (max_mev + 1 - y_min)
    y_positions = energies.copy()

    for _ in range(2 * last_idx):
        overlap_found = False
        for i in range(1, last_idx + 1):
            diff = y_positions[i] - y_positions[i-1]
            if diff < font_size_mev:
                overlap_found = True
                y_positions[i-1] += (diff - font_size_mev) / 2
                y_positions[i] += (font_size_mev - diff) / 2
                if y_positions[i-1] < y_min + font_size_mev / 2:
                    y_positions[i-1] = y_min + font_size_mev / 2
                    y_positions[i] = y_positions[i-1] + font_size_mev
        if not overlap_found:
            break

    # Draw levels and labels
    for i in range(0, last_idx + 1):
        fig.add_trace(go.Scatter(x=[0, 1], y=[energies[i], energies[i]], mode='lines', line=dict(color='black', width=1)))
        fig.add_trace(go.Scatter(x=[1.03, 1.1, 1.19], y=[energies[i], y_positions[i], y_positions[i]], mode='lines', line=dict(color='gray', width=1)))
        fig.add_annotation(x=1.2, y=y_positions[i], text=f"{energies[i]:.3f}, {spins[i]}", xanchor='left', font=dict(size=font_size), showarrow=False)

    # Draw separation energy thresholds
    if sn is not None and sn < max_mev:
        fig.add_trace(go.Scatter(x=[-0.6, -0.1], y=[sn, sn], mode='lines', line=dict(color='red', width=1)))
        fig.add_annotation(x=-0.6, y=sn, text=f"Sn {sn:.3f}", xanchor='left', yanchor='bottom', font=dict(size=font_size, color='red'), showarrow=False)

    if sp is not None and sp < max_mev:
        fig.add_trace(go.Scatter(x=[-0.6, -0.1], y=[sp, sp], mode='lines', line=dict(color='blue', width=1)))
        fig.add_annotation(x=-0.6, y=sp, text=f"Sp {sp:.3f}", xanchor='left', yanchor='bottom', font=dict(size=font_size, color='blue'), showarrow=False)

    fig.add_annotation(x=0.5, y=max_mev + 0.5, text=f"<b>{A}{symbol}</b>", font=dict(size=1.5 * font_size), showarrow=False)
    fig.add_annotation(x=0.5, y=-0.5, text="Exp", font=dict(size=1.5 * font_size), showarrow=False)
    fig.show()

# ==========================================
# MAIN EXECUTION BLOCK
# ==========================================
if __name__ == "__main__":
    target = "12C"
    max_energy = 19

    print_isotope_info(target)
    plot_energy_levels(target, max_energy)

    print("Execution Finished.")